# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: clone Bwild
          command: git clone "git@github.com:sinpaout/Bwild.git" --single-branch -b develop --depth 1
      - run:
          name: exec deploy
          command: |
            git config --global user.email "osekiharn@gmail.com"
            git config --global user.name "osekiharn"
            cd Bwild
            yarn
            yarn build:content
            yarn deploy
            cp -rf out/** ../docs && ls -alFG
            cd ..
            rm -rf Bwild
            git add -A .
            git commit -a --amend --no-edit
            git push -f origin HEAD
